Create UPP-1.md
UMAprotocol/UMIPs pull request #42
Opened 2020-08-31 20:44 UTC by mrice32

This proposes a lighter-weight form of an UMIP meant for simple parameter changes, like fees, inflation rewards, voting reward expiries, etc. The difference between this and an UMIP is semantic and process-based. Both still need tokenholder approval to be implemented and both can still pose a risk to the DVM.

2020-09-01 03:08 UTC, claytonroche commented on UPPs/upp-1.md
> +A successful UMIP will move along the following stages: Draft ⟶ Final ⟶ Approved.
UPP not UMIP

2020-09-01 03:09 UTC, claytonroche requested changes
Just need to fix the UMIP/UPP discrepancy

2020-09-01 18:14 UTC, mrice32 commented on UPPs/upp-1.md
> +A successful UMIP will move along the following stages: Draft ⟶ Final ⟶ Approved.
Thanks, fixed. PTAL.

2020-09-02 03:50 UTC, claytonroche approved these changes

2020-09-02 11:13 UTC, merged