Add Jarvis LP TVL KPI Option method doc
UMAprotocol/UMIPs pull request #470
Opened 2022-01-25 17:26 UTC by abg4

2022-01-25 22:28 UTC, Reinis-FRP commented on Implementations/jarvis-lp.md
> +Interval:daily,
Does this imply price intervals should be rounded down to 00:00:00 UTC? Or can use the latest available block at or before the request timestamp?

2022-01-25 22:28 UTC, Reinis-FRP commented on Implementations/jarvis-lp.md
> +      * `to`: request timestamp;
Where does start timestamp come from as its not in ancillary data?
But if KPI options should just track spot TVL (no need for TWAP) then `from` can be calculated as request timestamp less fixed offset. In order to ensure consistent results independent on when results are verified its better to set offset to 30 days so that CoinGecko granularity is fixed at hourly intervals.

2022-01-25 22:28 UTC, Reinis-FRP commented on Implementations/jarvis-lp.md
> +7. Sum both LP reserve balance values from Step 6 to get the total value of the pool in USD at the latest available block at or before the evaluation timestamp.
If `TVLCurrency` is passed in ancillary data then should replace USD here

2022-01-25 22:28 UTC, Reinis-FRP commented on Implementations/jarvis-lp.md
> +It is intended to deploy the documented KPI options separately on each supported chain using [LSP contract](https://github.com/UMAprotocol/protocol/blob/master/packages/core/contracts/financial-templ
If deployment on multiple chains is planned would this still track LP TVL on Polygon?

2022-01-26 14:44 UTC, abg4 commented on Implementations/jarvis-lp.md
> +Interval:daily,
Unless Sean disagrees, I think we can use the latest available block at or before the request timestamp. Let me know if you agree with the update I made to the interval.

2022-01-26 14:45 UTC, abg4 commented on Implementations/jarvis-lp.md
> +      * `to`: request timestamp;
Good call, I updated `from` under the assumption we are not using a TWAP.

2022-01-26 14:45 UTC, abg4 commented on Implementations/jarvis-lp.md
> +7. Sum both LP reserve balance values from Step 6 to get the total value of the pool in USD at the latest available block at or before the evaluation timestamp.
Updated to use `TVLCurrency`.

2022-01-26 14:46 UTC, Reinis-FRP submitted a review, later dismissed

2022-01-26 15:18 UTC, smb2796 commented on Implementations/jarvis-lp.md
> +      * `to`: request timestamp;
I think it is likely that we will need to use a TWAP and should design for that after confirming with Jarvis

2022-01-26 15:24 UTC, smb2796 commented on Implementations/jarvis-lp.md
> +It is intended to deploy the documented KPI options on Polygon using [LSP contract](https://github.com/UMAprotocol/protocol/blob/master/packages/core/contracts/financial-templates/long-short-pair/Lon
If I remember correctly, there is a desire to have a step function and not a strictly linear payout here. As there is no current way to bake this into our FPLs, we should account for this in `Implementation` and `Intended Application`.

Summarizing previous conversation around that:
- At expiry, 1M JRT is given out per 1M of liquidity.
- For the KPI option, payout should not be per $, but per tranche of $1M.
- So if there is $1.2M of liquidity, the KPI will deliver 1M JRT.
- $1.9M would also be 1M JRT
- But if we have $2.01M would deliver 2M

2022-01-26 15:26 UTC, smb2796 requested changes
Before merging, we should confirm and update accordingly:
- Use of TWAP
- Stepwise vs linear payout function

2022-01-27 03:35 UTC, smb2796 commented on Implementations/jarvis-lp.md
> +TVLCheckpoints:{"0":0,"1000000":1000000,"2000000":2000000,"3000000":3000000,"4000000":4000000}
What are these tvl checkpoints used for? Since "payout value" increases proportionally to TVL threshold, do you think we could just instruct voters to round TVL value down to nearest million? Or do you want to create more flexibility by passing these in?

2022-01-27 03:40 UTC, smb2796 submitted a review, later dismissed

2022-01-27 03:41 UTC, smb2796 commented
Personally think this looks really good! Just had one clarification question about the ancillary data

2022-01-27 14:16 UTC, abg4 commented on Implementations/jarvis-lp.md
> +TVLCheckpoints:{"0":0,"1000000":1000000,"2000000":2000000,"3000000":3000000,"4000000":4000000}
Yea, good question. I think we are clear in the `Intended Application` section on how voters should round TVL down to the nearest million. I saw the `TVLCheckpoints` parameter in the YEL implementation doc so main reasons for including was consistency with other TVL implementations and being explicit on the thresholds. I can easily remove it if you don't think it adds value being included here?

2022-01-27 14:28 UTC, Reinis-FRP commented on Implementations/jarvis-lp.md
> +TVLCheckpoints:{"0":0,"1000000":1000000,"2000000":2000000,"3000000":3000000,"4000000":4000000}
`TVLCheckpoints` was used for YEL because payouts per checkpoints were not linear.
If that is not required and checkpoints are in round millions then its simpler to use negative `Rounding` parameter (-6) as discussed in [UMIP-117](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-117.md). Just check if normal rounding (up from 5) works here. If you need floor rounding than this should be explicitly stated in the implementation.

2022-01-27 16:17 UTC, abg4 commented on Implementations/jarvis-lp.md
> +TVLCheckpoints:{"0":0,"1000000":1000000,"2000000":2000000,"3000000":3000000,"4000000":4000000}
Makes sense. I removed `TVLCheckpoints ` and updated the `Rounding` parameter to -6. We need to use floor rounding so I added a step to the implementation.

2022-01-27 16:24 UTC, smb2796 submitted a review, later dismissed

2022-01-27 17:07 UTC, Reinis-FRP approved these changes

2022-01-27 17:08 UTC, merged