feat: add optimistic asserter update umip
UMAprotocol/UMIPs pull request #574
Opened 2023-02-09 16:49 UTC by md0x

Signed-off-by: Pablo Maldonado <pablo@umaproject.org>

Add Optimistic Asserter update UMIP

2023-02-09 17:16 UTC, chrismaree submitted a review, later dismissed
this looks good to me!

2023-02-09 17:23 UTC, Reinis-FRP approved these changes

2023-02-10 11:29 UTC, mhairimcalpine commented on UMIPs/umip-oa-2.md
> +| Discourse Link | https://todo                           |
Discourse link - https://discourse.umaproject.org/t/add-optimistic-asserter-update/1914

2023-02-13 17:07 UTC, mhairimcalpine commented on UMIPs/umip-oa-2.md
> +
update placeholder addresses

2023-02-15 15:40 UTC, Reinis-FRP reviewed
please also update the name of this PR and md filename to reflect OOv3 naming

2023-02-15 15:43 UTC, md0x commented
> please also update the name of this PR and md filename to reflect OOv3 naming

Thanks, I've updated the PR name and decription

2023-02-15 15:51 UTC, smb2796 approved these changes

2023-02-15 18:18 UTC, mhairimcalpine requested changes

2023-02-15 18:18 UTC, mhairimcalpine commented on UMIPs/umip-172.md
> +
Replace placeholder addresses.

2023-02-15 21:09 UTC, Reinis-FRP commented on UMIPs/umip-172.md
> +
Please also add removal of `OptimisticAsserter` from `Finder` here

2023-02-15 21:09 UTC, chrismaree approved these changes

2023-02-15 21:17 UTC, md0x commented on UMIPs/umip-172.md
> +
https://github.com/UMAprotocol/UMIPs/pull/574/commits/9d8c9e767a6f08377916041377d17e0598bbadfe

2023-02-15 21:19 UTC, Reinis-FRP approved these changes

2023-02-15 22:11 UTC, merged