Adding stablespread ref impl
UMAprotocol/UMIPs pull request #98
Opened 2020-12-19 00:20 UTC by chicfilabae

Standalone script with minimal deps for computing the price of a STABLESPREAD index as detailed in UMIP #28

2020-12-19 00:46 UTC, nicholaspai commented on UMIPs/umip-28.md
> +As an example of how one may go about cosntructing such a feed programatically, here is one that was put together as a standalone script with minimal deps: https://gist.github.com/chicfilabae/3dff8ae
```suggestion
As an example of how one may go about constructing such a feed programmatically, here is one that was put together as a standalone script with minimal dependencies: https://gist.github.com/chicfilabae/3dff8aef233e4b9e5315daa7a835867d. As always, double-check the implementation as well as include additional measures for reliability to ensure reasonable assumptions around when the graph or Cryptowatch isn't available. 
```

2020-12-19 00:47 UTC, nicholaspai approved these changes
This is a great addition, left one nit. Another question on the `gist` specifically:

Isn't the script runnable without the CRYPTOWATCH_API_KEY? I recall their API having a free tier which would suffice for this script

2020-12-21 13:15 UTC, nicholaspai requested changes
In step (5) in the `implementation` section, do you think its worth making the resulting calculation symmetric and returning the minimum of step (5) currently and 2?

```
5. Perform the maximum of the result of step 4 and 0. This is to ensure non-negativity. 
6. Perform the minimum of the result of step 5 and 2.
```

2020-12-21 17:42 UTC, chicfilabae commented on UMIPs/umip-28.md
> +As an example of how one may go about cosntructing such a feed programatically, here is one that was put together as a standalone script with minimal deps: https://gist.github.com/chicfilabae/3dff8ae
Fixed.

2020-12-21 17:48 UTC, chicfilabae commented
Made changes where appropriate. Leaving the implementation as is for the steps, the extra min'ing is modifying the intended behavior

2020-12-21 17:53 UTC, nicholaspai submitted a review, later dismissed
@chicfilabae Thanks for addressing the changes. Do you think its worth adding the extra min-ing though in a subsequent PR?

2020-12-21 20:14 UTC, chicfilabae commented
I completely misunderstood your suggestion- I thought you meant step 5 and and step 2, which didn't make sense to me.

But yes, we should absolutely min by `2` for symmetry given the order of A and B shouldn't matter- good catch!

2020-12-21 20:23 UTC, smb2796 approved these changes
Great, thanks for the updates! Going to merge in and mark the UMIP as 'Last Call'.

2020-12-21 20:24 UTC, merged